const API='https://wqjzrbhbkienlxocykcn.supabase.co/functions/v1/piscinas-api';
const REPORTS='https://wqjzrbhbkienlxocykcn.supabase.co/functions/v1/piscinas-relatorios';
const piscinaId=Number(new URLSearchParams(location.search).get('piscina')||0);
const mesesNome=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
if(localStorage.getItem('logado')!=='true'||!localStorage.getItem('token'))location.href='login.html';
async function f(base,path){const h={Authorization:`Bearer ${localStorage.getItem('token')||''}`};const r=await fetch(`${base}${path}`,{headers:h});if(r.status===401){location.href='login.html';throw new Error('Sessão expirada')}if(r.status===428){location.href='senha.html';throw new Error('Troca de senha obrigatória')}return r;}
function tempo(seg){seg=Math.max(0,Math.floor(Number(seg)||0));const d=Math.floor(seg/86400);seg%=86400;const h=Math.floor(seg/3600);seg%=3600;const m=Math.floor(seg/60),s=seg%60;return d?`${d}d ${h}h ${m}m`:`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
const kwh=v=>`${Number(v||0).toFixed(3).replace('.',',')} kWh`;
const brl=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let relatorio=null;
async function carregarNome(){if(!piscinaId)return;const r=await f(API,'/piscinas');const ps=await r.json().catch(()=>[]);const p=Array.isArray(ps)?ps.find(x=>Number(x.id)===piscinaId):null;document.getElementById('piscinaNome').textContent=p?`${p.nome}${p.localizacao?' · '+p.localizacao:''}`:`Piscina #${piscinaId}`;}
function montarAnos(){const atual=new Date().getFullYear(),sel=document.getElementById('ano');for(let a=atual;a>=atual-5;a--){const o=document.createElement('option');o.value=a;o.textContent=a;sel.appendChild(o);}sel.value=atual;}
async function carregarRelatorio(){if(!piscinaId){alert('Piscina não informada.');location.href='index.html';return;}const ano=document.getElementById('ano').value;const r=await f(REPORTS,`/consumo/${piscinaId}/mensal?ano=${ano}`);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.erro||'Erro ao carregar relatório');relatorio=d;renderizar();}
function renderizar(){const meses=relatorio?.meses||[];const totalKwh=meses.reduce((s,m)=>s+Number(m.consumo_kwh||0),0),totalSeg=meses.reduce((s,m)=>s+Number(m.tempo_segundos||0),0),custos=meses.map(m=>m.custo_estimado).filter(v=>v!==null&&v!==undefined),totalCusto=custos.reduce((s,v)=>s+Number(v),0);document.getElementById('totalKwh').textContent=kwh(totalKwh);document.getElementById('totalTempo').textContent=tempo(totalSeg);document.getElementById('totalCusto').textContent=relatorio.tarifa_kwh==null?'Tarifa não cadastrada':brl(totalCusto);document.getElementById('potenciaRef').textContent=Number(relatorio.potencia_kw||0)>0?`${Number(relatorio.potencia_kw).toFixed(3).replace('.',',')} kW`:'Não configurada';const grid=document.getElementById('mesesGrid');grid.innerHTML='';meses.forEach(m=>{const b=document.createElement('button');b.type='button';b.className='month-card';b.dataset.month=m.mes;b.innerHTML=`<strong>${mesesNome[m.mes-1]}</strong><small>${kwh(m.consumo_kwh)}</small>`;b.onclick=()=>mostrarMes(m,b);grid.appendChild(b);});}
function mostrarMes(m,btn){document.querySelectorAll('.month-card').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('monthDetail').classList.remove('hidden');document.getElementById('mesTitulo').textContent=`${mesesNome[m.mes-1]} de ${relatorio.ano}`;document.getElementById('mesTempo').textContent=tempo(m.tempo_segundos);document.getElementById('mesKwh').textContent=kwh(m.consumo_kwh);document.getElementById('mesTarifa').textContent=relatorio.tarifa_kwh==null?'Não cadastrada':`${brl(relatorio.tarifa_kwh)} / kWh`;document.getElementById('mesCusto').textContent=m.custo_estimado==null?'Não disponível':brl(m.custo_estimado);document.getElementById('monthDetail').scrollIntoView({behavior:'smooth',block:'nearest'});}
document.getElementById('btnVoltar').onclick=()=>location.href=`agenda.html?piscina=${piscinaId}`;document.addEventListener('DOMContentLoaded',async()=>{montarAnos();document.getElementById('ano').addEventListener('change',carregarRelatorio);try{await Promise.all([carregarNome(),carregarRelatorio()]);}catch(e){alert(e.message||'Erro ao carregar gastos mensais');}});
